LinkYou/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('registration.backends.simple.urls'), name='registration_register'),
    url(r'^login$', auth_views.login, name='login'),
    url(r'^logout$', auth_views.logout, name='logout'),
    url(r'^', include('linkyouapp.urls')),
]

# For the medias in debug mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

linkyouapp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^collection/new$', views.CollectionCreateView.as_view(), name='new_collection'),
    url(r'^collection/(?P<slug>[\w-]+)-(?P<pk>\d+)$', views.CollectionDetailView.as_view(), name='collection_detail'),
    url(r'^collection/delete/(?P<slug>[\w-]+)-(?P<pk>\d+)$', views.CollectionDeleteView.as_view(), name='delete_collection'),
    url(r'^collection/edit/(?P<slug>[\w-]+)-(?P<pk>\d+)$', views.CollectionUpdateView.as_view(), name='update_collection'),
    url(r'^(?P<pk>\d+)-(?P<slug>[\w-]+)/link/new$', views.LinkCreateView.as_view(), name='new_link'),
    url(r'^favorite/new$', views.CreateFavoriteView.as_view(), name='new_favorite'),
    url(r'^favorite/delete/(?P<pk>\w+)$', views.DeleteFavoriteView.as_view(), name='delete_favorite'),
    url(r'^dashboard$', views.UserDashboardView.as_view(), name='dashboard'),
    url(r'^about$', views.About.as_view(), name='about'),            # The about page
    url(r'^discover$', views.Discover.as_view(), name='discover'),   # The discover collections page
    url(r'^link/edit/(?P<pk>\w+)$', views.LinkUpdateView.as_view(), name='update_link'),
    url(r'^link/delete/(?P<pk>\w+)$', views.LinkDeleteView.as_view(), name='delete_link'),
    url(r'^$', views.Home.as_view(), name='home'),                   # The homepage
]

linkyouapp/models.py
from django.db import models
from django.contrib.auth.models import User  # XXX get_user_model()
from django.utils.text import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver
from taggit.managers import TaggableManager

class Collection(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    image = models.ImageField(blank=True, upload_to='uploads/img/collections')
    private = models.BooleanField(default=False)
    tags = TaggableManager()
    user_it_belongs = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
            # Newly created object, so set slug
            self.slug = slugify(self.name)
            super(Collection, self).save(*args, **kwargs)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=255)
    favorites = models.ManyToManyField(
        Collection,
        through='Favorite',
        through_fields=('profile', 'collection'),
        )

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, *, raw=False, **kwargs):
    if raw:
        return False
    if created:
        Profile.objects.create(user=instance).save()

class Favorite(models.Model):
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return self.profile.user.username + " - " + self.collection.name

class Link(models.Model):
    url= models.URLField(max_length=2000)
    text = models.CharField(max_length=255)
    collection_it_belongs = models.ForeignKey(
        'Collection',
        on_delete=models.CASCADE,
        null=False,
        blank=False,
    )

    def __str__(self):
        return self.text

class BlackList(models.Model):
    url= models.URLField(max_length=2000)
    text = models.CharField(max_length=255)

    def __str__(self):
        return self.name

linkyouapp/forms.py
from django import forms
from .models import Collection, Link

class CollectionForm(forms.ModelForm):
    class Meta:
        model = Collection
        fields = {'name', 'image', 'tags', 'private'}
        widgets = {
                    'name': forms.TextInput(attrs={'placeholder': 'My great collection'}),
                }

class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = {'url', 'text'}
        widgets = {
                    'text': forms.TextInput(attrs={'placeholder': 'My new link'}),
                    'url': forms.TextInput(attrs={'placeholder': 'http://www.example.com'}),
                }

linkyouapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, DetailView, CreateView, UpdateView, DeleteView, ListView, View
from .models import Collection, Link, Favorite
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import CollectionForm, LinkForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.forms.formsets import formset_factory
from django.db import IntegrityError, transaction
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.contrib import messages


# Static pages related views
class Home(TemplateView):
    '''LinkYou homepage with concept description and call to action'''
    template_name = 'home.html'

    def best_collections(self):
        return Favorite.objects.filter()#filter(private=False)

    def collections(self):
        return Collection.objects.filter(private=False)


class About(TemplateView):
    '''You know, if we have the time to do it'''
    def get(self, request):
        return render(request, "about.html")

class Discover(ListView):
    '''The public page to discover users' collections'''
    template_name = 'discover.html'
    model = Collection
    context_object_name = 'collections'
    collections = []

    def get_queryset(self):
        if self.request.GET.get('q'):
            return Collection.objects.filter(tags__name__in=self.request.GET.get('q').split())
        else:
            return Collection.objects.filter(private=False)


# User related views
class UserDashboardView(LoginRequiredMixin, TemplateView):
    '''The dashboard of a user and his collections list'''
    template_name = "dashboard.html"

    def collections(self):
        return Collection.objects.filter(user_it_belongs=self.request.user)

    def favorites(self):
        return Favorite.objects.filter(profile=self.request.user.profile)

class UserProfileView(TemplateView):
    template_name = "profile.html"

# Collection related views
class CollectionDetailView(DetailView):
    '''Default view of a collection of links'''
    model = Collection
    template_name = "collection.html"

    def get_context_data(self, **kwargs):
        context = super(CollectionDetailView, self).get_context_data(**kwargs)
        canLike = True
        canModify = False
        if self.object.user_it_belongs == self.request.user:
            canLike = False
            canModify = True
        # XXX le test ci-dessus est un peu déconnecté des tests du dessous.
        if not self.request.user.is_authenticated:
            canLike = False
        elif Favorite.objects.filter(collection=self.object, profile=self.request.user.profile):
            canLike = False
        context['canLike']=canLike
        context['canModify'] = canModify
        return context

class CollectionCreateView(LoginRequiredMixin, CreateView):
    '''The view of a collection creation'''
    template_name = 'collection_form.html'
    model = Collection
    form_class = CollectionForm

    def form_valid(self, collection_form):
        self.object = collection_form.save(commit=False) # Used by the success_url
        new_collection = collection_form.save(commit=False) # Uncommitted to add creator
        new_collection.user_it_belongs = self.request.user # Add creator (request user)
        new_collection.save()
        collection_form.save_m2m()
        # super() is super!
        return self.get_success_url()

    def get_success_url(self):
         return redirect('new_link', pk=self.object.id, slug=self.object.slug)

class CollectionUpdateView(LoginRequiredMixin, UpdateView):
    '''Update collection view'''
    model = Collection
    form_class = CollectionForm
    template_name = "collection_form.html"
    success_url = reverse_lazy("dashboard")

    def dispatch(self, request, *args, **kwargs):
        collection = self.get_object()
        if collection.user_it_belongs != self.request.user:
            return HttpResponseForbidden("Access forbidden!")
        else:
            return super(CollectionUpdateView, self).dispatch(request, *args, **kwargs)

class CollectionDeleteView(LoginRequiredMixin, DeleteView):
    '''The delete view yeah'''
    model = Collection
    template_name = "collection_confirm_delete.html"
    success_url = reverse_lazy("dashboard")

    def dispatch(self, request, *args, **kwargs):
        collection = self.get_object()
        if collection.user_it_belongs != self.request.user:
            return HttpResponseForbidden("Access forbidden!")
        else:
            return super(CollectionDeleteView, self).dispatch(request, *args, **kwargs)

class LinkCreateView(LoginRequiredMixin, TemplateView):
    '''View of a link creation'''

    def get(self, request, *args, **kwargs):
        LinkFormSet = formset_factory(LinkForm, min_num=1, validate_min=True)

        collection_links = Link.objects.filter(collection_it_belongs=Collection.objects.get(pk=self.kwargs['pk']))

        if collection_links:
            if collection_links[0].collection_it_belongs.user_it_belongs != request.user:
                return HttpResponseForbidden("Access forbidden!")

        link_data = [{'text': l.text, 'url': l.url} for l in collection_links]
        link_formset = LinkFormSet(initial=link_data)
        return render(request, 'link_form.html', {'link_formset': link_formset,})

    def post(self, request, *args, **kwargs):
        LinkFormSet = formset_factory(LinkForm, min_num=1, validate_min=True)
        link_formset = LinkFormSet(request.POST)
        new_links = []

        if link_formset.is_valid():
            for link_form in link_formset:
                text = link_form.cleaned_data.get('text')
                url = link_form.cleaned_data.get('url')

                if text and url:
                    new_links.append(Link(collection_it_belongs=Collection.objects.get(pk=self.kwargs['pk']), text=text, url=url))

            try:
                Link.objects.filter(collection_it_belongs=Collection.objects.get(pk=self.kwargs['pk'])).delete()
                Link.objects.bulk_create(new_links)

                # And notify our users that it worked
                messages.success(request, 'Collection successfully updated !')
                return HttpResponseRedirect(reverse('collection_detail', kwargs={'pk':int(self.kwargs['pk']), 'slug': 'test'}))

            except IntegrityError: #If the transaction failed
                messages.error(request, 'There was an error saving your profile.')
                return redirect(reverse('profile-settings'))
        else:
            print(link_formset.errors)
            LinkFormSet = formset_factory(LinkForm, min_num=1, validate_min=True)
            collection_links = Link.objects.filter(collection_it_belongs=Collection.objects.get(pk=self.kwargs['pk']))
            link_data = [{'text': l.text, 'url': l.url} for l in collection_links]
            link_formset = LinkFormSet(initial=link_data)
            messages.info(request, "Please add at least one link!")
            return render(request, 'link_form.html', {'link_formset': link_formset,})



class CreateFavoriteView(LoginRequiredMixin, View):
    '''Favorite some collection'''

    model = Favorite
    def post(self, request):
        Favorite.objects.create(collection=Collection.objects.get(pk=int(request.POST.get('collection'))),profile=request.user.profile)
        messages.info(request, "Collection liked !")
        return redirect(request.META.get('HTTP_REFERER'))

class DeleteFavoriteView(LoginRequiredMixin, DeleteView):
    '''Delete a Favorite'''
    model = Favorite

    def get_success_url(self):
        return reverse("dashboard")


class LinkUpdateView(LoginRequiredMixin, UpdateView):
    '''Update link view'''
    model = Link
    form_class = LinkForm
    template_name = "link_form_simple.html"
    success_url = reverse_lazy("dashboard")

    def dispatch(self, request, *args, **kwargs):
        link = self.get_object()
        if link.collection_it_belongs.user_it_belongs != self.request.user:
            return HttpResponseForbidden("Access forbidden!")
        else:
            return super(LinkUpdateView, self).dispatch(request, *args, **kwargs)


class LinkDeleteView(LoginRequiredMixin, DeleteView):
    '''The delete form for the view'''
    model = Link
    template_name = "link_confirm_delete.html"

    def get_success_url(self):
        return reverse("collection_detail" , kwargs={"pk":self.object.collection_it_belongs.id, "slug":self.object.collection_it_belongs.slug})

    def dispatch(self, request, *args, **kwargs):
        link = self.get_object()
        if link.collection_it_belongs.user_it_belongs != self.request.user:
            return HttpResponseForbidden("Access forbidden!")
        else:
            return super(LinkDeleteView, self).dispatch(request, *args, **kwargs)

linkyouapp/templates/about.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
<h1>Hey what about linnkyou ?</h1>

<p>Who? What? When? Why?</p>
</div>


{% endblock %}

linkyouapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block meta %}{% endblock %}
  <title>LinkYou</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/linkyou.css' %}">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  {% block styles %}{% endblock %}

  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</head>
<body>

  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Linkyou</a>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'discover' %}">Discover</a>
          </li>
        </ul>

        {% if not user.is_authenticated %}
        <a href="{% url 'login' %}" class="btn btn-primary my-2 mx-1 my-sm-0">Login</a>
        <a href="{% url 'registration_register' %}" class="btn btn-outline-success my-2 ml-1 my-sm-0">Sign Up</a>
        {% else %}
        <a href="{% url 'dashboard' %}" class="btn btn-primary my-2 mx-1 my-sm-0">Dashboard</a>
        <a href="{% url 'logout' %}" class="btn btn-outline-danger my-2 mx-1 my-sm-0">Logout</a>
        {% endif %}

      </div>
    </div>
  </nav>

  {% block content %}{% endblock %}

<!--
  <footer class="footer">
    <div class="container">
      <span class="text-muted text-center">Linkyou 2017 - Debrot / Ducommun / Roy | Powered by django</span>
    </div>
  </footer>
-->

  {% block scripts %}{% endblock %}

</body>
</html>

linkyouapp/templates/collection.html
{% extends 'base.html' %}

{% block meta %}
<meta property="og:url"           content="{{request.build_absolute_uri}}" >
<meta property="og:type"          content="website" >
<meta property="og:title"         content="Linkyou Collection - {{collection.name}}" >
<meta property="og:description"   content="A LinkYou online ressources collection." >

{% if collection.image %}
<meta property="og:image"         content="{{collection.image.url}}" >
{% else %}
<meta property="og:image"         content="http://lorempicsum.com/futurama/350/200/1" >
{% endif %}

{% endblock %}


{% block scripts %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.8&appId=450415271956068";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<script>window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
  t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);

  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };

  return t;
}(document, "script", "twitter-wjs"));</script>

<script>

function openAll(){
  $(".linkyou-url").each(function(idx, alink){alink.click()})
}

</script>

{% endblock %}

{% block content %}


{% if collection.image %}
<div class="col-md-12 img-header" style="background-image: url('{{collection.image.url}}');">
  {% else %}
  <div class="col-md-12 dark-header">
    {% endif %}
    <div class="img-header-filter">
      <div class="container d-flex justify-content-between">
        <div>
          <div class="title-line d-flex justify-content-left">
            <h1>{{collection.name}}</h1>
            {% if canLike %}
            <div>
              <form method="post" action="/favorite/new/">
                {% csrf_token %}
                <input type="hidden" name="collection" value="{{collection.pk}}">
                <button class="btn btn-outline-secondary p-2 ml-4 mt-1" type="submit">I like it !</button>
              </form>
            </div>
            {% endif %}
          </div>
          <hr>
          <p class="card-text"><small>a collection by {{collection.user_it_belongs.username}}</small></p>
        </div>

      </div>
    </div>

    <div class="container">

      {% if messages %}
      <div class="messages alert alert-info" role="alert">
        {% for message in messages %}
        <strong{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</strong>
        {% endfor %}
      </div>
      {% endif %}

      <div class="d-flex justify-content-between">
        {% if canModify %}
        <a href="{% url "new_link" collection.pk collection.slug %}" type="button" class="btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i>
          &nbsp;Add link to collection</a>
          {% endif %}

          <!-- Button trigger modal -->
          <div>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal"><i class="fa fa-file-text-o" aria-hidden="true"></i>&nbsp;Get as text</button>
            <button type="button" class="btn btn-primary" onclick="openAll()"><i class="fa fa-file-text-o" aria-hidden="true"></i>&nbsp;Open all links</button>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myShareModal"><i class="fa fa-share-alt" aria-hidden="true"></i>
              &nbsp;Share</button>
            </div>
          </div>

          <ul class="list-group links-list py-2">
            {# SQL n°1 #}
            {% for l in collection.link_set.all %}
            <li class="list-group-item justify-content-between">
              <div>
                <img src="http://www.google.com/s2/favicons?domain={{l.url}}" alt="fav">&nbsp;
                <a href="{{l.url}}" target="_blank" rel="nofollow" class="linkyou-url">{{l.text}}</a> &nbsp;
              </div>
              {% if canModify %}
              <div>
                <a href="{% url "delete_link" l.pk %}" type="button" class="btn btn-default float-right mx-1">Delete</a>
                <a href="{% url "update_link" l.pk %}" type="button" class="btn btn-default float-right">Update</a>
              </div>
              {% endif %}
            </li>
            {% endfor %}
          </ul>




          <!-- Modal get as text -->
          <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">

                  {# SQL n°2 #}
                  {% for l in collection.link_set.all %}
                  {{l.url}};{{l.text}}<br>
                  {% endfor %}

                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary">Save changes</button>
                </div>
              </div>
            </div>
          </div>

          <!-- Modal get as text -->
          <div class="modal fade" id="myShareModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Share collection</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">

                  <a class="btn btn-primary" href="mailto:?subject=My Linkyou Collection&body={{request.build_absolute_uri}}"><i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;Send by mail</a>

                  <div class="btn btn-default" data-href="{{request.build_absolute_uri}}" data-layout="button_count" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse">Partager</a></div>

                  <a class="btn btn-primary"
                  href="https://twitter.com/intent/tweet?text=My%20Linkyou%20Collection" data-size="large">
                  Tweet</a>


                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary">Save changes</button>
                </div>
              </div>
            </div>
          </div>

          <div class="py-3">
            {% for tag in collection.tags.all %}
            <span class="badge badge-default p-2">{{tag.name}}</span>
            {% endfor %}
          </div>

        </div>


        {% endblock %}

linkyouapp/templates/collection_confirm_delete.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="container">
  <div class="card my-4">
    <div class="card-block">

      <form action="" method="post">
        {% csrf_token %}
        <div class="alert alert-danger" role="alert">
          Are you sure you want to delete the collection "{{ collection }}"?
        </div>
        <input type="submit" value="Confirm" />
      </form>

    </div>
  </div>
</div>
{% endblock %}

linkyouapp/templates/collection_form.html
{% extends 'base.html' %}

{% load app_filter %}

{% block content %}

<div class="container py-4">
  <div class="card">
    <div class="card-block">

      <h1>New collection</h1>
      <hr/>

      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
          <label>Name</label>
          {{form.name|addcss:"form-control form-control-lg"}}
        </div>

        <div class="form-group">
          <label>Illustration</label>
          {{form.image}}
        </div>

        <div class="form-group">
          <label>Tags</label>
          {{form.tags|addcss:"form-control form-control-lg"}}
        </div>

        <div class="form-group">
          <label>Private</label>
          {{form.private}}
        </div>

        <button type="submit" class="btn btn-primary">Create collection</button>
      </form>

    </div>
  </div>
</div>

{% endblock %}

linkyouapp/templates/dashboard.html
{% extends 'base.html' %}


{% block content %}

<div class="container py-3 mt-4">

  <div class="d-flex justify-content-between m3-4">
    <h2>Your collections</h2>
    <a href="{% url 'new_collection' %}" type="button" class="btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i>
      &nbsp;Create new collection</a>
    </div>

    <ul class="list-group py-3">
      {% for collection in view.collections %}

      <li class="list-group-item justify-content-between">
        <a href="{% url "collection_detail" collection.slug collection.pk %}">{{ collection.name }}</a> &nbsp;
        <div>
          <a href="{% url "delete_collection" collection.slug collection.pk %}" type="button" class="btn btn-default">Delete</a> &nbsp;
          <a href="{% url "update_collection" collection.slug collection.pk %}" type="button" class="btn btn-default">Update</a> &nbsp;
        </div>
      </li>
      {% empty %}

      <div class="card text-center">
        <div class="card-block">
          <span class="big-icon">
            <i class="fa fa-plus" aria-hidden="true"></i>
          </span>

          <h3>It's empty, <strong>start collecting links!</strong></h3>
          <p class="lead text-muted">
            Find the best resources for you and add them to a great new shareable collection right now!
          </p>
          <a href="{% url 'new_collection' %}" type="button" class="btn btn-outline-success"><i class="fa fa-plus" aria-hidden="true"></i>
            &nbsp;Create new collection</a>
          </div>
        </div>

        {% endfor %}
      </ul>

      <h2 class="mt-4 py-3">Collections you liked</h2>
      <ul class="list-group">
        {% for favorite in view.favorites %}

        <li class="list-group-item justify-content-between">
          <div>
            {# SELECT n+1 #}
            <a href="{% url "collection_detail" favorite.collection.slug favorite.collection.pk %}">{{favorite.collection}}</a> &nbsp;
            <span class="author">created by {{favorite.collection.user_it_belongs}}</span>
          </div>
          <form method="POST" action="{% url "delete_favorite" favorite.pk %}">
             {% csrf_token %}<input type="submit" value="Delete">
          </form>

        </li>
        {% empty %}
        <div class="card text-center">
          <div class="card-block">
            <span class="big-icon">
              <i class="fa fa-star" aria-hidden="true"></i>
            </span>

            <h3>Hey, <b>let's like some collections!</b></h3>
            <p class="lead text-muted">
              Why don't you go and find some interesting collections from other users?
            </p>
            <a href="{% url 'discover' %}" type="button" class="btn btn-outline-primary"><i class="fa fa-plus" aria-hidden="true"></i>
              &nbsp;Discover great collections</a>
            </div>
          </div>

          {% endfor %}
        </ul>

      </div>

      {% endblock %}

linkyouapp/templates/link_confirm_delete.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="container">
  <div class="card my-4">
    <div class="card-block">

      <form action="" method="post">
        {% csrf_token %}
          <div class="alert alert-danger" role="alert">
            Are you sure you want to delete the link : "{{ link.text }} ({{ link.url }})"?
          </div>
          <input type="submit" value="Confirm" />
      </form>

    </div>
  </div>
</div>
{% endblock %}